---
version: 2.1

# Reusable YAML fragments
main-env: &main-env
  docker:
    - image: circleci/buildpack-deps:buster

jobs:
  quality-checks:
    <<: *main-env
    steps:
      - checkout
      - run:
          name: Test code
          command: make test

workflows:
  version: 2
  ci:
    jobs:
      - quality-checks
