name: llp-ci

on:
  push:
  pull_request:
  release:
    types: [published]

env:
  PR_NUMBER: ${{ github.event.number }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Test code
        run: make test
